# 상속
```py
# 상속을 사용한 계층구조 변경
class Person:
    #공통적인 이름, 나이 초기화를 부모클래스에서 함
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def talk(self):  # 메서드 재사용
        print(f'반갑습니다. {self.name}입니다.')


class Professor(Person):
    def __init__(self, name, age, department):
        #self.name = name
        #self.age = age
        self.department = department


class Student(Person):
    def __init__(self, name, age, gpa):
        #self.name = name
        #self.age = age
        self.gpa = gpa
```

## 매서드 오버라이딩
- 부모클래스의 메서드를 같은 이름, 같은 파라미터 구조로 재정의함

- 참고: 메서드 오버로딩 - 같은 이름, 다른 파라미터 구조로 재정의 >> 파이썬에서는 미지원

## 다중상속
- 둘 이상의 상위클래스에서 상속받는 경우
- 상속 순서에 의해 결정됨
```py
# 다중 상속 예시
class Person:
    def __init__(self, name):
        self.name = name

    def greeting(self):
        return f'안녕, {self.name}'

#엄마클래스
class Mom(Person):
    gene = 'XX'

    def swim(self):
        return '엄마가 수영'

#아빠클래스
class Dad(Person):
    gene = 'XY'

    def walk(self):
        return '아빠가 걷기'

#아이클래스(아이가 먼저 그 다음 Dad, 그 다음 Mom)
class FirstChild(Dad, Mom):
    def swim(self):
        return '첫째가 수영'

    def cry(self):
        return '첫째가 응애'


baby1 = FirstChild('아가')
print(baby1.cry())  # 첫째의 메서드: 첫째가 응애
print(baby1.swim())  # 첫째의 메서드: 첫째가 수영
#엄마꺼도 있긴 한데 첫째에도 있으므로 첫째가 우선

print(baby1.walk())  # 아빠의 메서드: 아빠가 걷기
print(baby1.gene)  # Dad, Mom이므로 Dad가 우선
```
- 다이아몬드문제: 파이썬은 상속 순서로 해결
- Methood Resolution Order:메서드 결정순서 알고리즘

## super() 메서드
  - 우선순위가 높은 클래스 순서로 가져올 수 있음
  - 단순히 부모클래스의 메서드를 불러오는 것이 아니라 MRO 순서로 클래스를 호출할 수 있다.

  ```py
  # 단일 상속에서 예시
  class Person:
      def __init__(self, name, age, number, email):
          self.name = name
          self.age = age
          self.number = number
          self.email = email
  
  
  class Student(Person):
      def __init__(self, name, age, number, email,   student_id):
          # super()를 통해 Person의 __init__ 메서드   호출 == Person.__init__같음
          super().__init__(name, age, number, email)
          Person.__init__(name, age, number, email) # 단, Person 이름이 바뀌면 바꿔줘야해서 귀찮아짐
          self.stuednt_id = student_id
  ```

  ```py
  # 다중상속에서 예시
  class ParentA:
      def __init__(self):

          #A의 부모가 아니라 B를 호출하는 형태가 됨
          '''super().__init__()'''

          self.value_a = 'ParentA'

      def show_value(self):
          print(f'Value from ParentA: {self.value_a}')


  class ParentB:
      def __init__(self):
          self.value_b = 'ParentB'
  
      def show_value(self):
          print(f'Value from ParentB: {self.value_b}  ')
  
  
  class Child(ParentA, ParentB):
      def __init__(self):
          super().__init__()  # ParentA 클래스의   __init__ 메서드 호출
          self.value_c = 'Child'
  
      def show_value(self):
          super().show_value()  # ParentA 클래스의   show_value 메서드 호출
          print(f'Value from Child: {self.value_c}')
  
  
  child = Child()
  child.show_value()
  """
  Value from ParentA: ParentA
  Value from Child: Child
  """
  
  print(child.value_c)  # Child
  print(child.value_a)  # ParentA
  print(child.value_b)  
  # AttributeError: 'Child' object has no attribute 'value_b'
  """
  왜 이런 일이 벌어졌는가?: 파이썬 MRO 순서에 의해 parent A에서 멈춤
  어떻게 해결? >> ParentA에 super().__init__작성
  """

  """
  <ParentA에 super().__init__()를 추가하면?>
  그 다음으로 ParentB의 __init__가 실행되어 value_b도   초기화할 수 있음
  그러면 print(child.value_b)는 ParentB를 출력하게 됨
  
  print(child.value_b)  # ParentB
  """
  
  """
  <Child 클래스의 MRO>
  Child -> ParentA -> ParentB
  
  super()는 단순히 “직계 부모 클래스를 가리킨다”가   아니라, 
  MRO 순서를 기반으로 “현재 클래스의 다음 순서” 클래스  (또는 메서드)를 가리킴
  
  따라서 ParentA에서 super()를 부르면 MRO상 다음   클래스인 ParentB.__init__()가 호출됨
  """
  
  
  """
  1.1 Child 클래스의 인스턴스를 생성할 때 일어나는 일
      1. child = Child() 호출 시, Child.__init__()  가 실행

      2. Child.__init__() 내부에서 super().__init__  ()를 호출

          - 여기서 Child의 super()는 MRO에 의해   ParentA의 __init__()를 가리킴

      3. ParentA.__init__()로 진입
  
  1.2. ParentA.__init__() 내부
  	1. ParentA.__init__()에는 다시 super().  __init__()가 있음

  	2. ParentA를 기준으로 MRO에서 “다음 클래스”는   ParentB, 따라서 ParentA의 super().__init__()  는 ParentB.__init__() 호출
    
      3. ParentB.__init__()가 실행되면서 self.  value_b = 'ParentB'가 설정됨

  	4. ParentB.__init__()가 종료된 후, 다시   ParentA.__init__()로 돌아와 self.value_a =   'ParentA'가 설정됨

  	5. ParentA.__init__() 종료 후, 다시 Child.  __init__()로 돌아감

  	6. 마지막으로 Child.__init__() 내에서 self.  value_c = 'Child'가 설정되고 종료
  
  1.3 결과적으로 child 인스턴스는 value_a, value_b, value_c 세 속성을 모두 갖게 됨
  	- child.value_a → 'ParentA'
  	- child.value_b → 'ParentB' 
  	- child.value_c → 'Child'
  """
  ```
- .mro() 또는 ._ _mro_ _: 클래스의 우선순위 순서로 출력해줌

# 에러
## 문법에러: 애초에 프로그램이 실행되지 않음
- invalid syntax
- assign to literal
- EOL
- EOF

## 예외: 프로그램이 실행되었고 그 과정에서 에러발생

### 내장 예외
- ZeroDivisionError: 0나누기
- NameError: 변수 이름이 없음
- TypeError: 타입 불일치, 인자(누락, 초과, 불일치)
- ValueError: 부적절한 값
- IndexError: 인덱스 범위 벗어남
- KeyError: 딕셔너리에 키가 없음
- ModuleNotFoundError: 모듈 없음
- ImportError: import하려는게 없음
- KeyboardInterrupt: ctrl-c 혹은 delete 누르면
- IndentationError: 잘못된 들여쓰기

### 예외처리
- try: 예외가 발생할 수 있는 코드 무조건 실행
- except: 예외가 발생되었을 때 실행

- else
- finally: 예외와 상관 없이 항상 실행

### try-except 구조
- 물론 if else와도 같이 쓸 수 있음
```py
try:
    result = 10 / 0
    if x < 0:
        print('음수말고')
    else:
        print(f'입력한 숫자: {x}')

except ZeroDivisionError:
    print('0으로 나눌 수 없습니다.')
```

### 복수 예외 처리
```py
try:
    result = 10 / 0

#괄호 하나에 묶음
except (ZeroDivisionError, ValueError):
    print('ㅗ')

#또는
try:
    num = int(input('100을 나눌 값: '))
    print(100 / num)

#두 개의 except로 나눔
except ZeroDivisionError:
    print('0')

except ValueError:
    print('숫자')
```

### else-finally 추가
```py
#처음에 무조건 실행됨
try:
    x = int(input('숫자를 입력하세요: '))
    y = 10 / x

#예외상황1
except ZeroDivisionError:
    print('0으로 나눌 수 없습니다.')

#예외상황2
except ValueError:
    print('유효한 숫자가 아닙니다.')

#예외가 발생하지 않았다면 실행됨
else:
    print(f'결과: {y}')

#마지막에 무조건 실행됨
finally:
    print('프로그램이 종료되었습니다.')
```

### 예외처리 주의사항
- 예외처리 상속구조
- 구체적 >> 범용적 순서로 가야함
```py
try:
    num = int(input('100으로 나눌 값: '))
    print(100 / num)

#매우 상위 클래스
except BaseException:
    print('숫자를 넣어주세요.')

#위 보다 하위 클래스이므로 먼저 작성해야 함
except ZeroDivisionError:
    print('0으로 나눌 수 없습니다.')

#얘는 그냥 존재가 잘못됨
except:
    print('에러가 발생하였습니다.')


# 옳은 코드
# 가장 구체적인 예외부터 처리하고, 마지막에 범용 예외를 처리하도록 순서를 배치
try:
    num = int(input('100으로 나눌 값: '))
    print(100 / num)

#구체적인 예외부터
except ZeroDivisionError:
    print('0으로 나눌 수 없습니다.')

except ValueError:
    print('숫자를 넣어주세요.')

#선택사항: 마지막에 광범위한 예외(Exception)
except Exception:
    print('에러가 발생하였습니다.')
```

### as 키워드
- 예외 정보를 알아낼 수 있다.
```py
try:
    number = my_list[1]

except IndexError as error:
    # list index out of range가 발생했습니다.
    print(f'{error}가 발생했습니다.')
```

### EAFP, LBYL
- EAFP: 일단 지르고 본다. try-except
  - 예외 상황을 예측하기 어려울 때 유용

- LBYL: 돌다리도 두들긴다. if-else
  - 예외 상황을 미리 방지할 때 유용